ik_control_parameters:
  # threshold used to check whether a joint configuration has been reached by an arm (using sum of square errors - default 0.01 rad per joint)
  position_threshold: 0.0007
  # threshold used to check whether a an arm is still moving (using sum of square velocities - default 0.01 rad/s per joint)
  velocity_threshold: 0.0007
  # maximum hand velocity : avg is 2.0, closes completely [0.0->1.0] in half a second
  hand_max_velocity: 2.0
  # threshold on hand position to consider a desired one reached
  hand_position_threshold: 0.005
  # if false (default), wait for the controller
  kinematics_only: true
  # number of IK attempts (default: 10) and timeout (default: 0.005) of each attempt to use in default situations
  default_ik_attempts: 10
  default_ik_timeout: 0.005
  # error threshold to be used by KDLKinematicsPlugin (default: 0.001)
  epsilon: 0.001
  # if chain_group_names are specified, default groups are overwritten
  chain_group_names:
    - left_hand
    - right_hand
  # if tree_group_names are specified, default groups are overwritten
  tree_group_names:
    - full_robot
  # specify which are the parts of every tree in tree_group_names, chosen from groups defined in chain_group_names
  tree_composition:
    full_robot: [left_hand, right_hand]
  # group_map elements should correspond to what is declared in chain_group_names and tree_group_names
  group_map:
    left_hand: left_hand_arm
    right_hand: right_hand_arm
    full_robot: dual_hand_arm
    # right_arm: right_arm
    # left_arm: left_arm
  allowed_collision_prefixes:
    left_hand:
      - left_arm_7_link
      - left_hand
    right_hand:
      - right_arm_7_link
      - right_hand
  traj_pub_topics:
    left_hand: /left_arm/joint_trajectory_controller/command
    right_hand: /right_arm/joint_trajectory_controller/command
  hand_synergy_pub_topics:
    left_hand: /left_hand/joint_trajectory_controller/command
    right_hand: /right_hand/joint_trajectory_controller/command
  controller_map:
    left_hand: /left_arm/joint_trajectory_controller/follow_joint_trajectory/
    right_hand: /right_arm/joint_trajectory_controller/follow_joint_trajectory/
  hand_actuated_joint:
    left_hand: left_hand_synergy_joint
    right_hand: right_hand_synergy_joint
  motion_planner:
    planner_id: RRTstarkConfigDefault
    # the minimum timeout to use with the setPlanningTime function (will be the maximum between this value and the remaining movement time)
    planning_time: 3.0
    # number of attempts to be done at planning. nproc planners are launched at the same time, and the best result is returned.
    # If there is time left w.r.t. the timeout specified with setPlanningTime, more planners are launched
    max_planning_attempts: 16
    # backup parameters: if the first planning attempt fails, a new attempt is made with the backup planner. If this fails, too, an error is returned.
    backup_planner_id: RRTConnectkConfigDefault
    backup_planning_time: 5.0
    backup_max_planning_attempts: 16
    goal_position_tolerance: 0.001
    goal_orientation_tolerance: 0.005
    goal_joint_tolerance: 0.005
    workspace_bounds: [-1.2, -1.5, 0.1, 0.2, 1.5, 1.5]
  fix_start_state_collision:
    jiggle_fraction: 0.05
    max_sampling_attempts: 200
  slide:
    # for side C bottom table
    Object_PreSlide_R: [-0.03, 0.0, 0.25, 3.14, 2.75, 0.0] #parameter to use as pre-slide pose in object frame when sliding to right
    Object_Slide_R: [-0.03, 0.0, 0.17, 3.14, 2.75, 0.0] #parameter to use as slide pose in object frame when sliding to right
    Object_PreSlide_L: [0.03, 0.0, 0.25, 0.0, 2.75, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left
    Object_Slide_L: [0.03, 0.0, 0.17, 0.0, 2.75, 0.0] #parameter to use as slide pose in object frame when sliding to left
    Object_PreSlide_D: [0.0, 0.02, 0.25, 1.57, 2.75, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left    
    Object_Slide_D: [0.0, 0.02, 0.17, 1.57, 2.75, 0.0] #parameter to use as slide pose in object frame when sliding to left
    Object_PreSlide_U: [0.00, -0.02, 0.25, -1.57, 2.75, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left    
    Object_Slide_U: [0.00, -0.02, 0.17, -1.57, 2.75, 0.0] #parameter to use as slide pose in object frame when sliding to left
    # for side C top table
    Object_PreSlide_R_2: [-0.03, 0.0, -0.25, 0.0, -0.57, 0.0] #parameter to use as pre-slide pose in object frame when sliding to right
    Object_Slide_R_2: [-0.03, 0.0, -0.17, 0.0, -0.57, 0.0] #parameter to use as slide pose in object frame when sliding to right
    Object_PreSlide_L_2: [0.03, 0.0, -0.25, -3.14, -0.57, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left
    Object_Slide_L_2: [0.03, 0.0, -0.17, -3.14, -0.57, 0.0] #parameter to use as slide pose in object frame when sliding to left
    Object_PreSlide_U_2: [0.0, -0.02, -0.25, 1.57, -0.57, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left    
    Object_Slide_U_2: [0.0, -0.02, -0.17, 1.57, -0.57, 0.0] #parameter to use as slide pose in object frame when sliding to left
    Object_PreSlide_D_2: [0.00, 0.02, -0.25, -1.57, -0.57, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left    
    Object_Slide_D_2: [0.00, 0.02, -0.17, -1.57, -0.57, 0.0] #parameter to use as slide pose in object frame when sliding to left
    ee_contact: [0.0, 0.0, 0.20, 0.0, 0.00, 0.0] # parameter to use as pose for contact between the hand and the environment with respect to the end effector frame
    fixed_translation_bezier: 0.1
  tilt:
    # for side C bottom table
    Object_PreTilt_R: [-0.04, 0.0, 0.25, 3.14, 2.65, 0.0] #parameter to use as pre-slide pose in object frame when sliding to right
    Object_Tilt_R: [-0.04, 0.0, 0.17, 3.14, 2.65, 0.0] #parameter to use as slide pose in object frame when sliding to right
    Object_PreTilt_L: [-0.04, 0.0, 0.25, 3.14, 2.65, 0.0] #parameter to use as pre-slide pose in object frame when sliding to right
    Object_Tilt_L: [-0.04, 0.0, 0.17, 3.14, 2.65, 0.0] #parameter to use as slide pose in object frame when sliding to right
    #Object_PreTilt_L: [0.04, 0.0, 0.25, 0.0, 2.65, 0.0] CORRECT ONES #parameter to use as pre-slide pose in object frame when sliding to left
    #Object_Tilt_L: [0.04, 0.0, 0.17, 0.0, 2.65, 0.0] CORRECT ONES #parameter to use as slide pose in object frame when sliding to left
    Object_PreTilt_D: [0.0, -0.02, 0.25, 1.57, 2.55, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left    
    Object_Tilt_D: [0.0, -0.02, 0.17, 1.57, 2.55, 0.0] #parameter to use as slide pose in object frame when sliding to left
    Object_PreTilt_U: [0.00, 0.02, 0.25, -1.57, 2.55, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left    
    Object_Tilt_U: [0.00, 0.02, 0.17, -1.57, 2.55, 0.0] #parameter to use as slide pose in object frame when sliding to left
    # for side C top table
    Object_PreTilt_R_2: [-0.04, 0.0, -0.25, 0.0, -0.47, 0.0] #parameter to use as pre-slide pose in object frame when sliding to right
    Object_Tilt_R_2: [-0.04, 0.0, -0.17, 0.0, -0.47, 0.0] #parameter to use as slide pose in object frame when sliding to right
    Object_PreTilt_L_2: [0.04, 0.0, -0.25, -3.14, -0.47, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left
    Object_Tilt_L_2: [0.04, 0.0, -0.17, -3.14, -0.47, 0.0] #parameter to use as slide pose in object frame when sliding to left
    Object_PreTilt_U_2: [0.0, -0.02, -0.25, 1.57, -0.47, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left    
    Object_Tilt_U_2: [0.0, -0.02, -0.17, 1.57, -0.47, 0.0] #parameter to use as slide pose in object frame when sliding to left
    Object_PreTilt_D_2: [0.00, 0.02, -0.25, -1.57, -0.47, 0.0] #parameter to use as pre-slide pose in object frame when sliding to left    
    Object_Tilt_D_2: [0.00, 0.02, -0.17, -1.57, -0.47, 0.0] #parameter to use as slide pose in object frame when sliding to left
    ee_contact_t: [0.0, 0.0, 0.20, 0.0, 0.00, 0.0] # parameter to use as pose for contact between the hand and the environment with respect to the end effector frame